### PR TITLE
trigger image creation on push and schedule

### PR DESCRIPTION
**Pull request by petricm**
Any objection to have the image creation on `push` and on `schedule`?

### CODE REVIEW

**Comment by petricm** [comment]
The change is not what it runs the image creation on every push on master, so if you do a PR (and you are a decent person and don't do it from master) all should be fine. I wanted to limit this the job to repo (this can be done in gitlab) but as far as I see this cannot be done in github action, you can only limit the job to `refs/heds/...` see [here](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags)

**Comment by fstagni** [comment]
I think it's fine.

**Comment by petricm** [comment]
I am working on excluding the deploy when the secret is not present...

**Comment by petricm** [comment]
should be fine now

**Review by chrisburr — APPROVED** [review]

**Pull request merged**
