### PR TITLE
checkoutv4 and github_token

### PR DESCRIPTION
**Pull request by fstagni**

### CODE REVIEW

**Comment by chrisburr** [comment]
Why was this PR able to upload to dockerhub?

**Comment by fstagni** [comment]
The upload to dockerhub is done via username and password

**Comment by chrisburr** [comment]
But we wouldn’t want those secrets to be available to PRs?

**Comment by fstagni** [comment]
Indeed! There is some old and non-secure code here, I am looking into correcting it!

**Comment by fstagni** [comment]
https://github.com/DIRACGrid/management/pull/63 should be better, have a look (I did not fix the secrets yet)

**Pull request closed without merging**
