### PR TITLE
 Deploy globalDefaults.cfg and dirac-install.py to egi cvmfs for each push to repo

### LINKED ISSUE #10: globalDefaults.cfg : maintain in this repo, make sure it's uploaded
From https://github.com/DIRACGrid/DIRAC/issues/4604#issuecomment-630274040

Add globalDefaults.cfg (http://diracproject.web.cern.ch/diracproject/configs/globalDefaults.cfg) to this repo, and deploy to its current (and future) location(s) with the usual dirac-distribution container (like in https://github.com/DIRACGrid/Pilot/blob/master/.github/workflows/nightly.yml).

### PR DESCRIPTION
**Pull request by petricm**
Resolves #10
Now each push `globalDefaults.cfg` and `dirac-install.py` is deployed to egi cvmfs

@atsareg I have removed the download of this file from the sync_packages.py script that is used for the rest

Requires #32

### CODE REVIEW

**Review by atsareg — APPROVED** [review]

**Comment by atsareg** [comment]
@petricm : You do not have yet a cronjob github action on triggering release syncing in the cvmfs repo ?

**Comment by petricm** [comment]
> @petricm : You do not have yet a cronjob github action on triggering release syncing in the cvmfs repo ?

You have at the top the section
```yml
on:
  push:
  schedule:
    - cron:  '0 0 * * 0'
```
so one a week and on every push `dirac-install.py` and `globalDefaults.cfg` are updated

**Comment by atsareg** [comment]
I mean regular (daily) invocation of the  sync_packages.py script

**Comment by petricm** [comment]
The rest of the `sync_packages.py` code I have different plans how to automate it.

**Pull request merged**
