### PR TITLE
Add same check to VOMS_DIR and VOMSES as there is for CERT

### PR DESCRIPTION
**Pull request by petricm**
address DIRACGrid/DIRAC#5083

### CODE REVIEW

**Review by fstagni — APPROVED** [review]

**Comment by chaen** [comment]
I think there is a misunderstanding here. We were not expecting `dirac-install` do the test of an empty directory, but the `bashrc` itself

**Comment by petricm** [comment]
I can also add into the `bashrc` the same functionality, but currently there is a check in `dirac-install` only for `X509_CERT_DIR` and no check for `X509_VOMS_DIR` and `X509_VOMSES`. It's good to treat the variables the same.
@chaen so you would rather that I remove all checks for `X509` from `dirac-install` and move them into `bashrc` or have them both places?

**Comment by chaen** [comment]
I think having the check done at run time is best yes. Again, think of the case of the singularity container case that we have everytime in certification. But if there are more discussions to be have, let's have them on the issue, on on the PR

**Comment by petricm** [comment]
This adds now to the bachrc the following lines

```sh
# Function check if folder exist and contins files
function checkDir () {
  if [ -z "${1}" ]; then
    return 1
  fi
  if [ -n "$(ls -A "${1}" 2>/dev/null)" ]; then
    return 0
  fi
  return 1
}

if ! checkDir "$X509_CERT_DIR" ; then
  export X509_CERT_DIR="/etc/grid-security/certificates"
  if ! checkDir "$X509_CERT_DIR" ; then
    export X509_CERT_DIR="/tmp/mpetric/CC7/v7r3-pre7/etc/grid-security/certificates"
  fi
fi

if ! checkDir "$SSL_CERT_DIR" ; then
  export SSL_CERT_DIR="/etc/grid-security/certificates"
  if ! checkDir "$SSL_CERT_DIR" ; then
    export SSL_CERT_DIR="/tmp/mpetric/CC7/v7r3-pre7/etc/grid-security/certificates"
  fi
fi

if ! checkDir "$X509_VOMS_DIR" ; then
  export X509_VOMS_DIR="/etc/grid-security/vomsdir"
  if ! checkDir "$X509_VOMS_DIR" ; then
    export X509_VOMS_DIR="/tmp/mpetric/CC7/v7r3-pre7/etc/grid-security/vomsdir"
  fi
fi

if ! checkDir "$X509_VOMSES" ; then
  export X509_VOMSES="/etc/vomses"
  if ! checkDir "$X509_VOMSES" ; then
    export X509_VOMSES="/tmp/mpetric/CC7/v7r3-pre7/etc/grid-security/vomses"
  fi
fi
```

**Comment by petricm** [comment]
By default on a system `vomses` is directly in `/etc` only in the dirac case it's in `__proPath__/etc/grid-security/vomses`

**Comment by fstagni** [comment]
As agreed at today's hackathon, let's merge this one.

**Pull request merged**
